version: '3.9'

services:
  ExpressApp:
    container_name: App
    restart: always
    image: node
    build: .
    ports:
      - 3000:3000  
    volumes:
      - .:/usr/src/app
    links:
      - mongo
    command: npm run dev 

  mongo:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    command:
      mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db

  console:
    container_name: console
    build: .
    stdin_open: true
    tty: true
    ports:
      - 3001:3001  
    depends_on:
      - ExpressApp
    volumes:
      - .:/usr/src/app
    command: npm run client 